global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ai-attendance-web'
    static_configs:
      - targets: ['web:5000']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'ai-attendance-redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'ai-attendance-db'
    static_configs:
      - targets: ['database:5432']